name: General Issue
description: Use this template to create a new issue with topic details and progress tracking.
title: "[Topic] "
labels: ["Skill"]
assignees:
  - kzamanbd

body:
  - type: input
    id: topic-name
    attributes:
      label: Topic Name
      description: What is the main topic or title of this issue?
      placeholder: e.g., Implement login functionality
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed explanation of the issue or task.
      placeholder: Describe what needs to be done...
    validations:
      required: true

  - type: textarea
    id: progress
    attributes:
      label: Progress
      description: Track the current status or updates made.
      placeholder: e.g., Initial setup complete, working on backend integration...
    validations:
      required: false

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: List any links, documents, or references useful for this task.
      placeholder: Add links or notes here...
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Add any additional comments or context.
      placeholder: Any observations, blockers, or thoughts...
    validations:
      required: false
